import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercisesData = [
  // Upper Body / Chest & Back
  {
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    category: 'Chest',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 150,
    notes: 'Grip slightly outside shoulder-width, keep chest up, lower bar to level of nipples, avoid flaring elbows out.',
    pdfPage: 'Page 6',
    step1Setup: 'Lie down on the bench with eyes directly below racked bar. Use medium grip slightly wider than shoulder-width. Pull shoulder blades down/together to create small arch in lower back. Plant feet firmly.',
    step2Execution: 'Control weight down with elbows at 45-60 degree angle from torso. Lower until bar touches chest at sternum level.',
    step3Execution: 'Push bar up and back to starting position until arms fully lock out over shoulders.',
    additionalTips: 'Avoid bouncing bar against chest. Use control to touch chest lightly and use a spotter with heavy loads.',
    alternatives: JSON.stringify([
      'Flat Dumbbell Press (https://youtu.be/g14dhC5KYBM)',
      'Flat Machine Chest Press (https://youtu.be/sO8lFa9CidE)',
      'Flat Smith Machine Press (https://youtu.be/3Z3C44SXSQE)',
      'Seated Flat Cable Press (https://youtu.be/hPpNTAEDnxM)',
    ]),
  },
  {
    id: 'ex-db-chest-row',
    name: 'DB Chest Supported Row',
    category: 'Back',
    defaultSets: 3,
    targetReps: '10-12',
    minReps: 10,
    maxReps: 12,
    restSeconds: 120,
    notes: 'Set bench 2 notches up from bottom (30 deg), angle elbows out 45-60 deg, squeeze shoulder blades together.',
    pdfPage: 'Page 7',
    step1Setup: 'Set incline bench to ~30 degrees (second notch). Lay chest on bench with thumbless grip on dumbbells and arms hanging down.',
    step2Execution: 'Pull elbows back behind body at 45-60 degree angle away from torso. Squeeze shoulder blades together at top.',
    step3Execution: 'Control weight back down to starting position, letting shoulder blades open up before next rep.',
    additionalTips: 'Think about pulling with your elbows each rep to maximize lat and upper back activation.',
    alternatives: JSON.stringify([
      'Barbell Row (mid/upper back) (https://youtu.be/FTCmwlfZ29A)',
      'Seated Cable Row (https://youtu.be/Q-5V5T55giY)',
      'Chest Supported Machine Row (https://youtu.be/iDiVxqvHGWY)',
    ]),
  },
  {
    id: 'ex-ohp',
    name: 'Standing Barbell OHP',
    category: 'Shoulders',
    defaultSets: 3,
    targetReps: '6-8',
    minReps: 6,
    maxReps: 8,
    restSeconds: 150,
    notes: 'Press in straight line up, keep core and glutes engaged, avoid arching back or leg driving.',
    pdfPage: 'Page 8',
    step1Setup: 'Set bar in rack at armpit height. Grip just outside shoulder-width with forearms vertical. Step back with feet shoulder-width apart.',
    step2Execution: 'Squeeze glutes and brace core. Press bar vertically up, slightly tilting chin back until bar passes head, then press straight overhead to lock out.',
    step3Execution: 'Inhale and lower bar under control to upper chest with elbows at 45 degree angle in front.',
    additionalTips: 'Keep this a strict press by using only your upper body without bending knees or leg drive.',
    alternatives: JSON.stringify([
      'Seated DB Shoulder Press (https://youtu.be/DPXG3BJvl8A)',
      'Standing DB Shoulder Press (https://youtu.be/jWriqmLrQqs)',
      'Seated Neutral-Grip DB Press (https://youtu.be/W35eREjZnhI)',
    ]),
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    category: 'Back',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 120,
    notes: 'Grip outside shoulder width, lean back slightly (15 deg), pull bar to just under chin focusing on elbows.',
    pdfPage: 'Page 9',
    step1Setup: 'Adjust seat knee pads securely. Grab bar overhand outside shoulder-width. Sit with thighs locked under pad, leaning torso slightly back.',
    step2Execution: 'Pull elbows down and back until bar reaches chin level. Depress shoulder blades at top.',
    step3Execution: 'Control weight back up until arms are almost fully extended.',
    additionalTips: 'Try using a thumbless grip and pull through elbows rather than hands to isolate lats.',
    alternatives: JSON.stringify([
      'Weighted Pull-Ups (https://youtu.be/w_yuTRQd6HA)',
      'Kneeling One Arm Lat Pulldown (https://youtu.be/PkA-D-Ld4tE)',
      '3 Point Dumbbell Row (https://youtu.be/hrBLmuQ_vq8)',
    ]),
  },
  {
    id: 'ex-high-low-cable-fly',
    name: 'Standing High-to-Low Cable Flyes',
    category: 'Chest',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Set cables to highest position, use staggered stance, squeeze arms together down in front of hips.',
    pdfPage: 'Page 10',
    step1Setup: 'Set pulleys at highest position. Stand staggered in front with arms down in front of body and palms facing.',
    step2Execution: 'Control weight up with soft elbow bend to shoulder height, then squeeze lower chest to bring hands together down in front of hips.',
    step3Execution: 'Pause at bottom peak contraction before returning to starting position.',
    additionalTips: 'Think about bringing biceps together at bottom to maximize lower chest contraction.',
    alternatives: JSON.stringify([
      'Decline Dumbbell Press (https://youtu.be/pSOseCLdzIY)',
      'Banded Decline Push-Ups (https://youtu.be/LdahU9kB-u0)',
      'Decline Machine Chest Press (https://youtu.be/H4R-LiTJeH8)',
    ]),
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Cable Lateral Raises',
    category: 'Shoulders',
    defaultSets: 3,
    targetReps: '15-20',
    minReps: 15,
    maxReps: 20,
    restSeconds: 90,
    notes: 'Raise arm in scapular plane (15-30 deg forward), align cable with arm, think of pushing hand out not up.',
    pdfPage: 'Page 11',
    step1Setup: 'Attach handle to bottom pulley. Stand facing away from cable and reach behind body to grab handle.',
    step2Execution: 'Brace core and raise arm diagonally in scapular plane (15-30 degrees forward) up to shoulder height.',
    step3Execution: 'Lower under control back down behind thigh and repeat before switching arms.',
    additionalTips: 'Think about reaching hand out towards walls rather than pulling straight up to eliminate trap cheating.',
    alternatives: JSON.stringify([
      'Dumbbell Lateral Raise (https://youtu.be/zcO3sgAeLA0)',
      'Lying Incline Lateral Raise (https://youtu.be/upEqeI0F73M)',
      'Lean In Lateral Raise (https://youtu.be/2q4kjTDg-vs)',
    ]),
  },

  // Lower Body 1
  {
    id: 'ex-barbell-squat',
    name: 'Barbell Back Squat',
    category: 'Quads',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 150,
    notes: 'Experiment with foot stance, squat down to at least parallel, elevate heels onto weight plates if needed.',
    pdfPage: 'Page 16',
    step1Setup: 'Set bar at mid-chest height. Grip bar slightly wider than shoulder-width, duck under bar onto upper traps. Take 3 steps back with stance just outside shoulder-width (toes 15 deg out).',
    step2Execution: 'Brace core, squat straight down bending hips and knees with bar tracking over midfoot until thighs hit parallel or lower.',
    step3Execution: 'Reverse movement by extending legs while driving bar straight up vertically.',
    additionalTips: 'Elevate heels on 5lb weight plates if ankle mobility limits parallel depth.',
    alternatives: JSON.stringify([
      'Quad-Focused Leg Press (https://youtu.be/0nrW-q7-WRQ)',
      'Smith Machine Squat (https://youtu.be/zSVi51Jp3eI)',
      'Barbell Back Box Squat (https://youtu.be/QryQO4VuPK8)',
    ]),
  },
  {
    id: 'ex-db-rdl',
    name: 'Dumbbell Romanian Deadlift',
    category: 'Hamstrings',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 120,
    notes: 'Hinge hips straight back, keep dumbbells close to legs, descend to knee or mid-shin level until hamstrings stretch.',
    pdfPage: 'Page 17',
    step1Setup: 'Hold dumbbells by sides with shoulder-width stance (toes 15 deg out).',
    step2Execution: 'Contract abs, push hips straight back with slight knee bend, dragging dumbbells close to thighs down to knee or shin level.',
    step3Execution: 'Drive hips forward to return to standing position, squeezing glutes.',
    additionalTips: 'Think about pulling the floor back with your heels to engage hamstrings.',
    alternatives: JSON.stringify([
      'Barbell Romanian Deadlift (https://youtu.be/Q-2telZDPRw)',
      'Hyperextensions (https://youtu.be/RU5d2H_OmSc)',
    ]),
  },
  {
    id: 'ex-leg-extension',
    name: 'Seated Leg Extensions',
    category: 'Quads',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Align knees beside pivot point, extend legs fully, pause briefly at top contraction.',
    pdfPage: 'Page 18',
    step1Setup: 'Align knees beside machine pivot point with pad resting just above ankles (90 degree leg angle).',
    step2Execution: 'Pull up on side handles to anchor hips. Extend legs straight forward using quads.',
    step3Execution: 'Pause briefly at full extension at top before controlling weight back down.',
    additionalTips: 'Keep knees facing straight forward rather than rotating inward during extension.',
    alternatives: JSON.stringify([
      'Sissy Squat (https://youtu.be/3SeCC8ABZ_Q)',
      'Heel Elevated Goblet Squat (https://youtu.be/l9crMLuT4II)',
    ]),
  },
  {
    id: 'ex-walking-lunges',
    name: 'Walking Lunges (Quad-Focused)',
    category: 'Quads',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 120,
    notes: 'Take steps forward, keep torso upright, drive knee forward towards toes.',
    pdfPage: 'Page 19',
    step1Setup: 'Stand upright holding dumbbells by sides. Brace core.',
    step2Execution: 'Step forward, sink into lunge driving front knee forward over toes until front thigh is parallel to floor.',
    step3Execution: 'Push through front heel to step feet together, then repeat on opposite leg.',
    additionalTips: 'Keep 80-90% weight in front working leg and use back leg only for balance.',
    alternatives: JSON.stringify([
      'Heel Elevated Split Squat (https://youtu.be/bJE0-eZLa6E)',
      'Bulgarian Split Squat (https://youtu.be/r9XtxWSTlcg)',
    ]),
  },
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Weighted Calf Raises',
    category: 'Calves',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Feet hip width apart, elevate toes on weight plate for full stretch, press up on big toes.',
    pdfPage: 'Page 20',
    step1Setup: 'Stand hip-width apart holding dumbbells or barbell with toes elevated on weight plate.',
    step2Execution: 'Push straight up onto toes as far as possible, putting pressure on big toes.',
    step3Execution: 'Lower heels down under control for a 2-second stretch before next rep.',
    additionalTips: 'Place a weight plate under toes for extended range of motion stretch.',
    alternatives: JSON.stringify([
      'Single Leg Weighted Calf Raise (https://youtu.be/cRKA_Qdut7I)',
      'Leg Press Calf Raise (https://youtu.be/s8yUXsZrgE0)',
    ]),
  },

  // Push
  {
    id: 'ex-low-incline-db-press',
    name: 'Low Incline Dumbbell Press',
    category: 'Chest',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 150,
    notes: 'Set bench 1-2 notches up from bottom (15-30 deg), keep chest up, avoid flaring elbows out.',
    pdfPage: 'Page 24',
    step1Setup: 'Set bench to 15-30 degrees (1st-2nd notch). Kick dumbbells into position straight over shoulders.',
    step2Execution: 'Lower weight with elbows at 45-60 degree angle until dumbbells reach chest level.',
    step3Execution: 'Press weight straight up and in, bringing arms together at top lockout.',
    additionalTips: 'Retract shoulder blades into bench to isolate upper chest.',
    alternatives: JSON.stringify([
      'Incline Machine Chest Press (https://youtu.be/abc1fisYB3w)',
      'Low Incline Smith Machine Press (https://youtu.be/R53nThQcdZo)',
      'Low Incline Barbell Press (https://youtu.be/jW4j7FoqudI)',
    ]),
  },
  {
    id: 'ex-seated-mid-chest-fly',
    name: 'Seated Mid-Chest Cable Flyes',
    category: 'Chest',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Set cables to chest height, squeeze arms together, pause at end peak position.',
    pdfPage: 'Page 25',
    step1Setup: 'Position bench in center of cable machine at 75 degree angle. Set cable height at mid-chest.',
    step2Execution: 'Bring handles together in front with elbows slightly bent, squeezing chest.',
    step3Execution: 'Pause at peak contraction, then slowly open arms until elbows reach torso level.',
    additionalTips: 'Squeeze biceps in as if bringing them together for maximal chest recruitment.',
    alternatives: JSON.stringify([
      'Standing Mid-Chest Cable Fly (https://youtu.be/fyFVaCP9J-8)',
      'Pec-Deck Machine Fly (https://youtu.be/rnV3y1P7894)',
    ]),
  },
  {
    id: 'ex-flat-db-press',
    name: 'Flat Dumbbell Press',
    category: 'Chest',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 120,
    notes: 'Keep chest up, avoid flaring elbows out, control the weight up and down.',
    pdfPage: 'Page 26',
    step1Setup: 'Lay back on flat bench with dumbbells over shoulders and lower back slightly arched.',
    step2Execution: 'Lower dumbbells with elbows tucked at 45-60 degrees to torso level.',
    step3Execution: 'Press straight back up to full lockout over chest.',
    additionalTips: 'Plant feet firmly into ground for leg drive stability.',
    alternatives: JSON.stringify([
      'Barbell Bench Press (https://youtu.be/pCGVSBk0bIQ)',
      'Flat Machine Chest Press (https://youtu.be/sO8lFa9CidE)',
    ]),
  },
  {
    id: 'ex-db-lateral-raise',
    name: 'Dumbbell Lateral Raises',
    category: 'Shoulders',
    defaultSets: 3,
    targetReps: '15-20',
    minReps: 15,
    maxReps: 20,
    restSeconds: 90,
    notes: 'Lean torso forward slightly (15 deg), raise arms in scapular Y plane, avoid momentum.',
    pdfPage: 'Page 27',
    step1Setup: 'Stand shoulder-width apart holding dumbbells, leaning torso 15 degrees forward.',
    step2Execution: 'Raise dumbbells out in front in Y scapular plane (15-30 deg forward) to shoulder height.',
    step3Execution: 'Lower dumbbells under control down in front of thighs before next rep.',
    additionalTips: 'Use a thumbless grip and think about pushing hands out towards walls.',
    alternatives: JSON.stringify([
      'Cable Lateral Raise (https://youtu.be/1muit9qEctY)',
      'Lying Incline Lateral Raise (https://youtu.be/upEqeI0F73M)',
    ]),
  },
  {
    id: 'ex-incline-overhead-ext',
    name: 'Incline DB Overhead Extensions',
    category: 'Triceps',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Set bench to 45 degrees, move arms parallel to torso, keep upper elbows locked overhead.',
    pdfPage: 'Page 28',
    step1Setup: 'Set bench to 45 degrees (2-3 notches). Lay back with arms overhead parallel to torso.',
    step2Execution: 'Keep upper elbows locked overhead and bend forearms back behind head as far as possible.',
    step3Execution: 'Extend forearms back to starting overhead position to lockout triceps.',
    additionalTips: 'Keep elbows fixed in space overhead to stretch the triceps long head.',
    alternatives: JSON.stringify([
      'Overhead Rope Extensions (https://youtu.be/7yoTblFCUQM)',
      'Cable Pushdowns (https://youtu.be/MlfCS_7ZLXA)',
    ]),
  },
  {
    id: 'ex-cable-pushdowns',
    name: 'Cable Pushdowns (Elbow Friendly)',
    category: 'Triceps',
    defaultSets: 2,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Use two rope attachments if possible, keep elbows locked to sides, push down and out.',
    pdfPage: 'Page 29',
    step1Setup: 'Set top pulley height. Use two rope attachments, stepping back with 30 deg forward torso lean.',
    step2Execution: 'Keep elbows locked at sides, extend forearms down and spread ropes apart at bottom.',
    step3Execution: 'Control hands back up to chest height while keeping elbows stationary.',
    additionalTips: 'Using two rope attachments allows longer full range of motion lockout.',
    alternatives: JSON.stringify([
      'Incline DB Overhead Extensions (https://youtu.be/3d86xMhHROA)',
      'Overhead Rope Extensions (https://youtu.be/7yoTblFCUQM)',
    ]),
  },

  // Pull
  {
    id: 'ex-pull-ups',
    name: '(Weighted) Pull-Ups',
    category: 'Back',
    defaultSets: 3,
    targetReps: '6-12',
    minReps: 6,
    maxReps: 12,
    restSeconds: 150,
    notes: 'Grip outside shoulder-width, pull until chin over bar, use alternative if unable to do 6 reps.',
    pdfPage: 'Page 33',
    step1Setup: 'Grip bar overhand wider than shoulder-width. Hang with feet together and core engaged.',
    step2Execution: 'Depress shoulders down, pull elbows into back pockets, bringing chest up to bar.',
    step3Execution: 'Lower body under control until arms are almost fully straightened.',
    additionalTips: 'Think about pulling elbows down into back pockets rather than pulling with hands.',
    alternatives: JSON.stringify([
      'Lat Pulldown (https://youtu.be/AvYZZhEl7Xk)',
      'Kneeling One Arm Lat Pulldown (https://youtu.be/PkA-D-Ld4tE)',
      '3 Point Dumbbell Row (https://youtu.be/hrBLmuQ_vq8)',
    ]),
  },
  {
    id: 'ex-lat-cable-row',
    name: 'Lat Focused Cable Row',
    category: 'Back',
    defaultSets: 3,
    targetReps: '10-12',
    minReps: 10,
    maxReps: 12,
    restSeconds: 120,
    notes: 'Lean torso forward slightly, pull elbows down and back, keep elbows tight to sides.',
    pdfPage: 'Page 34',
    step1Setup: 'Sit with knees slightly bent. Lean torso slightly forward over hips.',
    step2Execution: 'Pull elbows down and back towards back pockets, keeping elbows tucked close to sides.',
    step3Execution: 'Stop when elbows reach torso, control weight back until arms extend.',
    additionalTips: 'Keep elbows tucked to sides to maximize lower lat fiber recruitment.',
    alternatives: JSON.stringify([
      'Chest Supported DB Row (https://youtu.be/I2Unz9FR0sc)',
      'Barbell Row (lat focus) (https://youtu.be/tS5lKXxtNvE)',
    ]),
  },
  {
    id: 'ex-rear-delt-cable-row',
    name: 'Rear Delt Cable Row',
    category: 'Shoulders',
    defaultSets: 3,
    targetReps: '12-15',
    minReps: 12,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Use wide handle outside shoulder-width, pull elbows at 45 degree angle as far back as possible.',
    pdfPage: 'Page 35',
    step1Setup: 'Use wide attachment with hands outside shoulder-width.',
    step2Execution: 'Pull handle towards sternum with elbows flared out at 45 degree angle.',
    step3Execution: 'Pull elbows back as far behind body as possible to squeeze rear delts.',
    additionalTips: 'Think about pulling with elbows rather than hands to target rear delts.',
    alternatives: JSON.stringify([
      'Chest Supported DB Rear Delt Row (https://youtu.be/6LTUVaKpRCk)',
      'Rear Delt Cable Fly (https://youtu.be/2Xepcd9FYvE)',
    ]),
  },
  {
    id: 'ex-incline-db-curls',
    name: 'Incline Dumbbell Curls',
    category: 'Biceps',
    defaultSets: 2,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 90,
    notes: 'Set bench 2-3 notches down from top (60 deg), alternate arms each rep, keep upper elbow locked.',
    pdfPage: 'Page 36',
    step1Setup: 'Set bench to 60 degrees. Lay back with arms hanging straight down with palms in.',
    step2Execution: 'Keep upper elbows locked back. Curl dumbbell up while supinating wrist to face ceiling at top.',
    step3Execution: 'Lower weight under control back to full arm extension before repeating.',
    additionalTips: 'Allowing arms to hang back stretches long head of biceps.',
    alternatives: JSON.stringify([
      'Behind Body Cable Curls (https://youtu.be/S2CNDlAY8kY)',
      'Barbell Curl (https://youtu.be/-ClfZ00zo8c)',
    ]),
  },
  {
    id: 'ex-hammer-curls',
    name: 'Hammer Curls',
    category: 'Biceps',
    defaultSets: 2,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 90,
    notes: 'Use neutral hammer grip, pull up and across chest, alternate arms each rep.',
    pdfPage: 'Page 37',
    step1Setup: 'Stand upright holding dumbbells in neutral grip with palms facing each other.',
    step2Execution: 'Curl one dumbbell up and slightly across chest keeping neutral grip.',
    step3Execution: 'Control weight down to full lockout before alternating to other arm.',
    additionalTips: 'Target brachialis and forearms by keeping neutral grip throughout.',
    alternatives: JSON.stringify([
      'Rope Cable Curls (neutral grip) (https://youtu.be/0vEzBCydrU0)',
    ]),
  },
  {
    id: 'ex-face-pulls',
    name: 'Standing Face Pulls',
    category: 'Shoulders',
    defaultSets: 2,
    targetReps: '10',
    minReps: 10,
    maxReps: 12,
    restSeconds: 60,
    notes: 'Use double rope attachment at top pulley, light weight, pull to forehead with 90 deg elbow bend then Y-raise.',
    pdfPage: 'Page 38',
    step1Setup: 'Set top pulley with double rope attachment. Stand back with arms straight.',
    step2Execution: 'Pull rope handles toward forehead while pulling elbows back to 90 degree biceps flex pose.',
    step3Execution: 'Raise arms into Y position overhead before returning to start.',
    additionalTips: 'Keep weight light and focus on external shoulder rotation at end of pull.',
    alternatives: JSON.stringify([
      'Bent Over Dumbbell Face Pulls (https://youtu.be/kA415Unr-_E)',
      'Wall Slides (https://youtu.be/x4zjfuLXHVk)',
    ]),
  },

  // Lower Body 2
  {
    id: 'ex-barbell-deadlift',
    name: 'Barbell Deadlift',
    category: 'Hamstrings',
    defaultSets: 3,
    targetReps: '6-8',
    minReps: 6,
    maxReps: 8,
    restSeconds: 150,
    notes: 'Hip-width stance, grip outside knees, keep head/back/hips in straight line, wedge into bar.',
    pdfPage: 'Page 42',
    step1Setup: 'Stand under bar over midfoot with feet hip-width apart. Hinge hips back, grip bar shoulder-width just outside knees. Bring bar to shins.',
    step2Execution: 'Engage lats to wedge into bar, brace core, push feet away from floor keeping bar close to legs.',
    step3Execution: 'Drive hips forward at top to squeeze glutes into full lockout.',
    additionalTips: 'If back rounds, elevate starting bar height onto weight plates.',
    alternatives: JSON.stringify([
      'Sumo Deadlift (https://youtu.be/9rXKd-_DaRs)',
      'Trap Bar Deadlift (https://youtu.be/5mnlJtf-7WM)',
      'Dumbbell Romanian Deadlift (https://youtu.be/Xu4DxwKWzl4)',
    ]),
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squat (Glute Focused)',
    category: 'Glutes',
    defaultSets: 3,
    targetReps: '8-10',
    minReps: 8,
    maxReps: 10,
    restSeconds: 60,
    notes: 'Use wider foot stance, lean torso forward slightly over front leg to emphasize glutes.',
    pdfPage: 'Page 43',
    step1Setup: 'Elevate rear foot on bench. Take wider stance and lean torso slightly forward.',
    step2Execution: 'Squat down driving back knee toward ground until front thigh is parallel to floor.',
    step3Execution: 'Push through front heel to drive hips up back to start.',
    additionalTips: 'Keep 80-90% weight in front working leg and rest 1 minute between legs.',
    alternatives: JSON.stringify([
      'Front Foot Elevated Reverse Lunges (https://youtu.be/JySEdVXPUM8)',
      'Weighted Step-Ups (https://youtu.be/Cjc3AgmdtlA)',
    ]),
  },
  {
    id: 'ex-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'Glutes',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 120,
    notes: 'Squeeze glutes hard, knees 90 degrees at top position, chin tucked down.',
    pdfPage: 'Page 44',
    step1Setup: 'Lay with upper back against bench and barbell padded over hips. Feet shoulder-width apart (90 deg knee angle at top).',
    step2Execution: 'Tuck chin down, squeeze glutes and drive through heels to push hips up vertically.',
    step3Execution: 'Pause for 1-2 seconds at top lockout before controlling weight back halfway down.',
    additionalTips: 'Keep chin tucked down throughout movement to prevent lower back arching.',
    alternatives: JSON.stringify([
      'Smith Machine Hip Thrust (https://youtu.be/srYETmyq3_c)',
      'Single Leg Hip Thrusts (https://youtu.be/FKD9-qezw08)',
    ]),
  },
  {
    id: 'ex-lying-leg-curls',
    name: 'Lying Leg Curls',
    category: 'Hamstrings',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Pull down on handles, avoid over-arching lower back, control weight up and down.',
    pdfPage: 'Page 45',
    step1Setup: 'Set pad above heel. Position knees beside pivot point with thighs on pad.',
    step2Execution: 'Pull down on handles, curl pad up toward glutes as far as possible.',
    step3Execution: 'Control weight back down until legs almost fully extend before next rep.',
    additionalTips: 'Avoid fully extending legs at bottom to keep constant hamstring tension.',
    alternatives: JSON.stringify([
      'Seated Leg Curls (https://youtu.be/81umRgyxIAU)',
      'Swiss Ball Leg Curls (https://youtu.be/uRBpd65dbYs)',
    ]),
  },
  {
    id: 'ex-seated-calf-raise',
    name: 'Seated Weighted Calf Raises',
    category: 'Calves',
    defaultSets: 3,
    targetReps: '10-15',
    minReps: 10,
    maxReps: 15,
    restSeconds: 90,
    notes: 'Point toes forward, lower heels as far as possible for stretch, press up on big toes.',
    pdfPage: 'Page 46',
    step1Setup: 'Sit on bench with toes on weight plate (90 deg knee angle) and dumbbells on thighs.',
    step2Execution: 'Push straight up onto toes as far as possible with pressure on big toe.',
    step3Execution: 'Slowly lower heels down to bottom stretch before repeating.',
    additionalTips: 'Seated calf raises specifically target the soleus muscle.',
    alternatives: JSON.stringify([
      'Seated Bodyweight Calf Raise (https://youtu.be/jW-cNnwRJ7E)',
    ]),
  }
];

const defaultUser = {
  id: 'user-bws-default',
  email: 'athlete@bws.com',
  name: 'BWS Athlete',
  unit: 'kg',
};

const routinesData = [
  {
    id: 'routine-upper-body',
    title: 'Upper Body Workout',
    focus: 'Upper Body (Chest, Back, Shoulders)',
    description: 'High volume BWS Upper Body workout targeting total upper body hypertrophy.',
    exerciseIds: JSON.stringify([
      'ex-bench-press',
      'ex-db-chest-row',
      'ex-ohp',
      'ex-lat-pulldown',
      'ex-high-low-cable-fly',
      'ex-cable-lateral-raise',
    ]),
  },
  {
    id: 'routine-lower-body-1',
    title: 'Lower Body 1 (Quad-Focused)',
    focus: 'Quads, Calves & Hamstrings',
    description: 'Primary BWS lower body routine emphasizing Quad strength and hypertrophy.',
    exerciseIds: JSON.stringify([
      'ex-barbell-squat',
      'ex-db-rdl',
      'ex-leg-extension',
      'ex-walking-lunges',
      'ex-standing-calf-raise',
    ]),
  },
  {
    id: 'routine-push',
    title: 'Push Workout',
    focus: 'Chest, Shoulders & Triceps',
    description: 'Targeted pressing workout for upper body pushes, front/side delts and triceps extension.',
    exerciseIds: JSON.stringify([
      'ex-low-incline-db-press',
      'ex-seated-mid-chest-fly',
      'ex-flat-db-press',
      'ex-db-lateral-raise',
      'ex-incline-overhead-ext',
      'ex-cable-pushdowns',
    ]),
  },
  {
    id: 'routine-pull',
    title: 'Pull Workout',
    focus: 'Back, Rear Delts & Biceps',
    description: 'Comprehensive pulling session for vertical/horizontal lat back volume, biceps and rear deltoids.',
    exerciseIds: JSON.stringify([
      'ex-pull-ups',
      'ex-lat-cable-row',
      'ex-rear-delt-cable-row',
      'ex-incline-db-curls',
      'ex-hammer-curls',
      'ex-face-pulls',
    ]),
  },
  {
    id: 'routine-lower-body-2',
    title: 'Lower Body 2 (Glute-Focused)',
    focus: 'Glutes, Hamstrings & Calves',
    description: 'Secondary BWS lower body session emphasizing posterior chain, glute hypertrophy and calves.',
    exerciseIds: JSON.stringify([
      'ex-barbell-deadlift',
      'ex-bulgarian-split-squat',
      'ex-hip-thrust',
      'ex-lying-leg-curls',
      'ex-seated-calf-raise',
    ]),
  },
];

async function seed() {
  console.log('🌱 Ingesting Step 1 / Step 2 / Step 3 PDF Cues from Official BWS Manual...');

  await prisma.user.upsert({
    where: { id: defaultUser.id },
    update: {},
    create: defaultUser,
  });

  for (const ex of exercisesData) {
    await prisma.exercise.upsert({
      where: { id: ex.id },
      update: ex,
      create: ex,
    });
  }

  for (const r of routinesData) {
    await prisma.routine.upsert({
      where: { id: r.id },
      update: r,
      create: r,
    });
  }

  console.log('✅ Successfully seeded Step 1 Setup, Step 2 Execution, and Additional Tips for all 25 BWS exercises!');
}

seed()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
